import 'package:flutter/material.dart';

void main() {
  runApp(LudoBoardApp());
}

class LudoBoardApp extends StatelessWidget {
  const LudoBoardApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(title: Text("Simple Boxes")),
        body: Column(
          children: [
            Row(
              //Row1
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
              ],
            ),
            Row(
              //Row2
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
              ],
            ),
            Row(
              //row3
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
              ],
            ),
            Row(
              //row4
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
              ],
            ),
            Row(
              //Row5
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
              ],
            ),

            Row(
              //Row6
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
              ],
            ),
            Row(
              //Row6
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
              ],
            ),
            Row(
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
              ],
            ),
            Row(
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
              ],
            ),
            Row(
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
              ],
            ),
            Row(
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
              ],
            ),
            Row(
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
              ],
            ),
            Row(
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
              ],
            ),
            Row(
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
              ],
            ),
            Row(
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
              ],
            ),
            Row(
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.green,
                  margin: EdgeInsets.all(2),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
