import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(home: ManualLudoBoard(), debugShowCheckedModeBanner: false),
  );
}

class ManualLudoBoard extends StatelessWidget {
  final double boxSize = 24.0;

  const ManualLudoBoard({super.key});

  Widget box(Color color) {
    return Container(
      width: boxSize,
      height: boxSize,
      decoration: BoxDecoration(
        color: color,
        border: Border.all(color: Colors.black, width: 0.5),
      ),
    );
  }

  Widget row(List<Color> colors) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: colors.map((c) => box(c)).toList(),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.pink[50],
      body: SingleChildScrollView(
        child: Center(
          child: Column(
            children: [
              row([
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.white,
                Colors.white,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
              ]),
              row([
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.white,
                Colors.white,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
              ]),
              row([
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.white,
                Colors.white,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
              ]),
              row([
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.white,
                Colors.white,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
              ]),
              row([
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.white,
                Colors.white,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
              ]),
              row([
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.white,
                Colors.white,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
              ]),
              row([
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.grey[300]!,
                Colors.grey[300]!,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
              ]),
              row([
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.grey[300]!,
                Colors.grey[800]!,
                Colors.grey[300]!,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
              ]),
              row([
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.grey[300]!,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
              ]),
              row([
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.white,
                Colors.white,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
              ]),
              row([
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.white,
                Colors.white,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
              ]),
              row([
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.white,
                Colors.white,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
              ]),
              row([
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.white,
                Colors.white,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
              ]),
              row([
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.white,
                Colors.white,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
              ]),
              row([
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.white,
                Colors.white,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
              ]),
            ],
          ),
        ),
      ),
    );
  }
}
